kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: paddock-pitcrew
  name: pitcrew-driver
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"paddock:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"pitcrew\")].image"}]'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: paddock-pitcrew
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app.kubernetes.io/component: paddock-pitcrew
      name: paddock-pitcrew
    spec:
      containers:
        - image: paddock:latest
          imagePullPolicy: Always
          name: pitcrew
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-app
                  key: dbname
            - name: B4MAD_RACING_COACH
              value: tbd
          envFrom:
            - secretRef:
                name: paddock-settings
          command: ["/bin/sh", "-c"]
          args:
            - python /opt/app-root/src/manage.py pitcrew
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 0
              memory: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      serviceAccount: paddock
      serviceAccountName: paddock
      volumes:
        - name: django-metrics-dir
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
